### ISSUE TITLE
When using a small restaurant size (2x6), appliance panel doesn't show up

### ISSUE THREAD

**Issue by bekarau** [plateupplanner/plateupplanner.github.io#1]
When using a very small restaurant size, the appliance panel disappears and doesn't appear to be able to be brought back.

Using Firefox 103 on OSX, using a full-screen (1920x1080) browser layout.

**Comment by bekarau** [comment]
<img width="1920" alt="Screen Shot 2022-10-04 at 2 02 53 pm" src="https://user-images.githubusercontent.com/16297184/193725493-0ee06646-7c6e-4fe6-954f-32f92324acff.png">

Scrolled all the way over to the right; the panel can be seen, but it's completely collapsed. Clicking on it doesn't change its behaviour.

**Comment by plateupplanner** [comment]
Thanks for the bug report! It should be fixed now :)
