### ISSUE TITLE
The added up list doesn't group some items properly 

### ISSUE THREAD

**Issue by JaviAZ** [plateupplanner/plateupplanner.github.io#10]
Idk if this is a known issue, but some items aren't always grouping for the count list at the bottom left, I [link ](https://plateupplanner.github.io/#G4RgBAnAHiCsYAYEFckrcgFk1AvApqgEICyANggM4DCqOCA7rACYL4CaATgqRSANJ109EWjHiMkgMYApLDQoARAOaom3CADZUChACMAWsXIIAggHEhVyaIl3h6Wcgb1MAB1QdWu3AEU1sMYUAOoAqtaiEYyYDLFxEtY0rPQ0Vi4OUWmRNg72CZLAAEze1NwAtoVZGTlW2NXZeXaZNRjpzZFtLbZIDDGx+Q31Q+0onYNCjWIj010ZY8OTAwvjs1XTQA) the plan I was doing for reference

**Comment by DiemasMichiels** [comment]
Correct!

Rotated items cause the Tally component to count them separately. Will be resolved in #9.

**Comment by JaviAZ** [comment]
That's great thanks!
