### ISSUE TITLE
[Idea] Add Notes/Icons to Placed Appliances

### ISSUE THREAD

**Issue by Sempiternity87** [plateupplanner/plateupplanner.github.io#17]
It would be great if it was possible to place notes on appliances. For example, if I wanted to mark a number for a teleporter, or specify what a smart grabber is filtered for, I currently can't do that, but this is very important for planning large automations.

**Comment by plateupplanner** [comment]
Thanks for the suggestion -- I will add this to our Discord and close this issue for the sake of organisation. Unfortunately this would be a completely new functionality and would take time to implement (especially with sharing), so I can't guarantee that we can do this (but feel free to come discuss in Discord)
