### ISSUE TITLE
Ctrl+Left Click+Drag to Copy

### ISSUE THREAD

**Issue by hawkerm** [plateupplanner/plateupplanner.github.io#18]
The copy button just places the item at the top-left corner, it'd be nice if you could press Ctrl while starting to drag an item to create a copy (leaving the original behind instead of the normal move).

This would make it pretty quick to put a bunch of tables or counters in a row.

(The orientation should also be copied.)

**Comment by plateupplanner** [comment]
Hi, thanks for the suggestion! I've just fixed the issue with the orientation, let me know if you run into any issues.

About the duplication, the copy button places the new copy wherever the mouse is, defaulting to top left only if the mouse is on an existing item or not on the grid at all. So you can control where your duplication goes by putting your mouse on an empty spot.

Closing for now; if you have further suggestions and/or would really prefer Ctrl + drag for duplication, please let us know in our Discord (where all the suggestions have been compiled) https://discord.gg/hqy2YmQbyf

**Comment by hawkerm** [comment]
@plateupplanner thanks for the response. But if I'm clicking the copy button with my mouse, how is it supposed to use my mouse's position over the grid? It's over the button?

(Ah, just saw there's `Ctrl+D` keyboard shortcut, that wasn't immediately obvious. Tooltips over the buttons to show their function and shortcut key could help.)
