### ISSUE TITLE
Import/Export Functionality

### ISSUE THREAD

**Issue by cookies-xor-cream** [plateupplanner/plateupplanner.github.io#2]
Hi, I saw someone asked for import/export functionality, and so I tried my hand at implementing them (got it all functional but the UX is sorely lacking at the moment).
Never really contributed to an 'open source' project and was wondering if someone here could guide me as to good etiquette when it comes to forks/PRs.

I've currently made a fork of the project with a feature branch containing what I would like. Where should I PR to when I'm ready?

**Comment by plateupplanner** [comment]
Hiya, great to have more people contributing to this project! ❤️ Since it's currently just me, all you need to do is open a PR and I will review and merge it if it looks ok. However, I think we should discuss how / what you're implementing exactly before opening the PR. I'm actually also in the middle of building something similar, so perhaps we can combine efforts?

I've opened a Discord server so we can discuss this a bit more easily: https://discord.gg/s3ewqEZh and we can update this issue when we've figured out next steps.

**Comment by plateupplanner** [comment]
Updating this issue so we can keep track. We decided to encode the JSON of the layout in the URI after the `#` so that people can share layouts and access them using the link. The URI will update automatically whenever the layout is changed, and exporting the layout would just be putting the URI onto the clipboard. When `App` mounts, we'll check whether there's anything that can be parsed after the `#` and if so load the layout.

**Comment by cookies-xor-cream** [comment]
URLs generator with the JSON are very very big. 41kb with no optimization on an empty layout
I managed to get it to <7kb on a maximum layout that was *full*.

I think this might be short enough that we can use a URL shortener on it but I'm not sure as to pricing (I don't believe they are free?) but I personally like to see what's in my URLs. It's of course your project and I highly doubt there would be a large malicious userbase passing off dodgy links as plateup layouts.

I believe if we are smart about how we store objects we can reduce this down to 1,000 character (1kb) uncompressed, and potentially a sensible length when compressed.

My idea is to do some of the computation at runtime rather than storing it in the database. Things like the path to the image are currently getting stored. For example "starter-hob.png". I can try to instead store the index as an offset into the SquareType `appliances`.

This would break backwards compatibility, we can try giving appliances a *key* property so their array would be 3 long.

[Here's the URL embedded](http://localhost:3000/#eyJ3aWR0aCI6MTYsImhlaWdodCI6MTIsImxheW91dCI6W1t7ImltYWdlUGHEJyJyb2xsaW5nLXBpbi5wbmciLMYeQWx0IjoiUsYdIFBpbiIsIm9yZGVyIjoyNSwicm90YXRpb24iOjB9LHsiY2xhc3NOYW1lIjoibGluZS1lbXB0eSLEG8xsa2l0Y2hlbi1mbG9vci1wcm90ZWN0b3LSeEvGKSBGxCkgUMgp6wCENP8AhP8AhP8AhP8AhP8AhP8AhP8AhP8AhP8AhP8AhOoAhHdva3PScVdva3PLXjPfXtlec2VyduQCVmJvYXJk02hTxiAgQsUgy3Iy33LZcv8CyP8CyN9sz2xkaW7Ea3RhYmxl0m1ExR4gVMQey243327ZbnNoYXJwLWtuaWbTbVPEHSBLxB3LbDbfbNpscGVjaWFscy1tZW510m5cIlPHIVwiIE1lbnXKdDPfdNp0dHJheS1zdGFuZNJxVHJheSBTxBzLajjfatlqc3VwcGxpZfQCkMcay2b/AbDEZndhbGzSZeUBr2N1dGxlcnnTasQfIEPGH8tv/wKN+gDVbmFwa2lu8wDUTsYZy2T/BC3aZGJyZWFkc3RpY/QENELKHcts/wPJ2mxjYW5kbGUtYm940mtDxRwgQm94y2rvBKVdLFvdbN8b3xvfG98b3xvYG+kCaN813zXfGt9p32nfGt8a3xrfGv8BVt8b3xvfG/8Aod8a2xrbad8b3xvaG+UDO+0HVWVzZWFyY2gtZGVza/MHV8cfIERlc2vqA5I2/wTM+wRobHVlcHJpbnQtY2FiaW5ldNJ0QsgjIEPGI8t4/wTg2nhoZWF0ZWQtbWl4ZfMJhkjFHiBNxB7Lbv8E4tpucmFwadltUsQd0Wz/CYn5Bo1jb252ZXlvcthuQ8cg0XEx33H5AN1wb3LENdRtUMgbymg1Od9o2Whjb23kAf/TZ0PHGstm/wgy2mb3ATfwAS4w32DZYP8DYf8DYd9w/wNh/wNh/wNh33jZePYA6cp17wDq/wpW2nJjb3B55Aul1nBDxh7Qbv8J9PkDZ3RyYeQCcvMJHVTHGstl/wLz/Ax3c2NvdfkBRETHH/AA1f8C/dpwd2Vs9gsuV8YZymQ3/wMB22RvcmstYm9vdNRnb3JrIELEHMtq7wSZ/wnu3xvfG/8Hp9813xvfa9813xvfG98b3xvfG98b3xvfG98b3xvfG98b1Rv/CdvfGt9p3xvfG98b+An1ZGlzcGz6D5NExh/wD5Y3/wij+wYcb29r+gWqQsYe7wTVN/8JffkFqmR1bWJ3YWl09AfWRMkcy2n/BvP6ANfFQeUSJ2VybWluYWzScU/HIyBUxyPLeP8H4/kA4WFwcGz0BbRBxRjLYf8G7PoA2ekSJPoA2egSJvQA2f8H0tp4YnVyZ2VyLWJ19BDtQsUdIEJ17BDxOP8Gl9psY2FycvUGlEPGGctk/wKK22RoZWVz8xPTQ8UYy2L/A1raYucBMnBhdHT1B8jnATVQxiDLcv8L/tpyY2hyaXN0bWFzLWNyYWNr9QkTQ8gkIEPHJMt6/wNv23r/AbL/AbL/A1v/AbH/AbHfYclhaG9i0l5Ib2LKW/8BmfsBH29mZmX0ALzFGMphOP8EeNti/wH7/wH78QH7/wna3xvfG/8HjN813xvfa9813xvfG98b3xvfG98b3xvfG98b/wFD31DfG99r3xrfGt9p3xvfG9sb8QnZZWdn8wOURWdn7AOG/wef+gQAZmlzaNJeRmlzaMte/wh12l5ob3QtZG9n9wf+SG90ZG9n8Af+/w9p2m1pY2UtY3JlYW3SakljZSBDxBvKaDn/BZXfaN9o32jfaO0BPfkBOesBNTn/CTPaZWZsb3XzC1VGxBfKYDj/EI7fYN9g32DdYP8CYv8CYt9t0G1udfQIq0517AioOd9e+QhHbXVzaHJvb23TYk3IG8tn/wEy+gDFdGhpY2stbWVh8xRGVMQcIE1lYesUPzn/BFzdam7aaW7QaP8EZvkBOf8Blv8Blv8AxSJzdGFydGVyLfUJ5lPGHSDtCe7/A4zaa29saXb0C/FPxRjKYTEw/xNP/wZs3xvfG98b3xvfG/8HlN8a2Rrfad813xvfG98b3xv/AKHfNd8a3xrfGt8a3xr/ANHfG98b3xv8CW9vafQR82nrEQwxMP8D4voD4v8F5P8F5N9o/wUT/wUT317/BKj/BKjfY9Nj/wGG/wGG8QJrzFxtaWNyb3dhdvMPWE3IG8po/w9a2WZvbmlv9AiTT8UYymAxMP8Q2foBJXDENm/0AYpQxxrMZ/8Q39pndG9t12dUxxrMZ/8BMPkBMHJpY/MBkVJpY+sBjDEw/xJp+wDFdXJrZfMl2VTFGMxj/wjv2mN3aW7zAMJXaW7tAML/CObaX/8B7v8B7v8Bh/8Ct/8Ct9hi/wPc/wPc313XXf8EnP8JRNpl/wbH3zXfNd813zXfNd813zXfNd813zXfNd813zXfNd013xvfG98b/wCh3xrfGt9p3zXfG9Ub8QlD/wh+/wh+/wSh/wlD/wlD32f/Dyb/Dybfadlp/w8l/w8l32fHZ9Ziz13/B7z6BXZsZXR0dfQHwEzGGctk/wfC+QDBa2V0Y2h1cNJjS8YZy2P/BprZY2115A/t8x89TcYZy2P/B1/ZY3NhZmV0efcQTcUc7hBM/wDL2WhnYXMtbGlt9h8yR2FzIEzGHcpq7QLAM9Vq9gH8/xUP/xUP32jLaP8VD/8VD99l/xSv/xSv/wGX/xSu/xSu/wUp2Wz/F9r/F9r/ASn/GJbHXu8FFP8JY/8Gsd8a3xrfad813zXfGt8a32nfNd813xrfGt8a3xrfGt8a3xrfGt8a3xrVGv8Bbd813xvVG/EJWv8fruUDhP8frv8D8PgD8P8gispi/whE22L/IajJYv8HfNti/yJty2T/B3jaZP8k7/8k799s1mz/JCn/JCnfcs9ycm9jY29sadNsxxrKZjf/BrnbZmVh9QE+xBfLYP8Hhdpg/ycLxGz/JwvfeNd4/yflymL/B5baYsVB/yi+xyP/KL7feM94/ymg/ymg32r/C0H/C0HfafkMb/897cl1/z3t/z3t/wFW/wFW/wFW32r/Ajj/Ajj7Ajj/CejfG98b/wd13xrfGt8a/wCd3zXfGt9p2GnfG98b3xvfG98b/wDX3xrXGt9p3xrfGt8a3xrfGt0a/y/Q8gQA/y/Q/wQD8wd1/y/Q/y/Q327Qbv80pf80pd9kyGT/NKX/NKXfasxq/zZJ/zZJ32bJZv82Sf82Sd9w03DoOobSa+g6gMpmNf8IO9pmc2NydWJi5UR2cnX0ELJTyCEgQsQhy3T/Bu/adHJvYm90LWJ1Zmb1O8zEHiBCxR7Lbv8C7NpuZGlzaC3kDYvSa0Rpc2ggUmFj6wGwNf8Dwtpo5gir+ADW5gig8QDW/wL02m7mAURtb/MVkuYBQU1v6xWUNf8Dxtxo/0Yi/0Yi1mz2FZ3/RbP/RbPXa/8DXf8DXf8DXd9m32bdZv8Jxt8b3xvfG98b3xvfG98b3xvfG98b3xvfG98b3xvfG98b3xvfG98b1xv/CTXfGt9p3xvfG98bxxvyE8H/A5H/A/fYaP8D999m32bfZt9m32bfZt9m32bfZstmc21hcnQtZ3JhYmL0Bz1TxB8gR8Yfy3D/EanfcN9w33DfcN9w33DfcN9w/ydk/ydk32fMZ/kA0fIAy/8Hqt9k32TfZN9k32TfZN9k/wID/wID/wID3HD/UKvFXv9Qq+4F0cxd/0/M/0/M2m3/ATv/ATv/ATvfcN9w33DScP8Jwd8b3xv/B3HfGtoa22nfG9cb32vfNd813zXfNd8b3xvfG/8Aod813xvfG98b2Rv/AjHfGt9p3xvPG/8Juv8IiP8G0foD+t9m32bfZt9m32bfZv8G1f8G1d9k32TfZN9k/wZr32PfY99j/wXw/wXw32/fb99v32/Vb/cBpWFzLW92ZXJyaWTzB63kJo5Pxx7Kbt9t2m3/AN3/AN3ccPUBTP8DS/8DS/8A1d9m32bfZv8DTf8C6t9k/wNN32PfY/8Ax99k32TfZP8CZv8CZv8Jov8Gnd8b2Rv/ByPfNd813zXfGt9p32nfNd813xrfGtxp3xvXG99r3xvfG99r3xrfGt8a/wCd3zXRGvEJm/8Djf8Djf8D/f8D/d9w33D/BTTGb/9VnP9VnN9nymf/VZv/VZvfZchl/1Wax1//VZraX/9XOf9XOd5x9gIM/wGd/wGd32j/AZ7/AZ7fZv8C2v8C2v8C2t9w/wjY/wjY2mb2Cu//HmL/HmLfc/8IhP8IhP8IhN1k/wGt/wGt3HD/Cur/Aaz/Aaz/ANX/ANX/ANXfcP8Bqf8Bqf8Jvf8G2P8G2N8a32nfNd813zXfNd813zXfGt8a32nfNd8b3xvfa98a3Brfad8a3xrfGt8a/wEh3xvzCbz/BZ3/BZ3/A/T/Bnb/BMr/BMrfZv8A2v8A2t902HT/BT7/BT7fcP8FPv8FPt9k2WT/Aa7/Aa7/Bt3/Aa3/Aa3/Aa3/ANn/Aa3/Aa3ccP8Re/8BrP8BrP8CEN9k32T/AMffY99j/wDH32TfZN9k32TfZN9k/wEr32PfY/8Ax99k32TfZN9k32QwfV1dLCJlbGVtZW50cyI6/3FEzVv/KFrGX+8AqP8yNMpd/zI09TI032nfad9p32nfad9p32nFaf8gLcZD8iAtzEP/cL3/cL3ZV/8CJv8CJtNR/yC7/yC71VP/Krn/KrnUUf9wUf9wUdpZ/3A2/3A20U//cBv/cBvOS/9wAf9wAdZV/2/m/m/mzEn/b8v/b8vTUf9vsP9vsNFP/2kS/2kS11X/aPfEWf9o99td/2w9/2w91VP/bCL/bCLTUf8Uz/8Uz9lX/xS0/xS0/xSZykz/FJnSS/8WHfoWHf8Civ8Civ8Civ8Civ8Civ8Cis5d/2tm/2tmz1f/a0v/a0vVU/806P806M1L/zTN/zTN11X/Nlb+NlbNSf82O/82O9BP/zfM/zfM11X/N7H/N7HVU/88cf88cdFPxSb/PFbHI/88VtNd/z9Nykf/B/f/QAz/QAz+A4P/Qg3/Qg3TUf9Cwv5Cws1J/0NtyUf/AoT/QoL/QoLYV/9E58Vb/0Tn3V//AUb/AUb/AUb/AUbTR/9mQfVmQcxA/0WcyUbzRZz/AXb/AXb/AXbOX/9KMsZD/gNQ/0rTxkP+A/D/S4L/S4LUUv9NAP9NAN9N303eTf9NMv9NMsxK/00Xx0XzTRffRd9F/wHA/wHA/wHAyFL/Uq7FQ/NSrsxD/1KU/1KUz03/Unr/UnrUT/9SYP9SYP8BLP8BLNFD/2FQ/2FQ0lD/V/HJRvRcjc1I/1iW9liW/wIG/wIG203/AWr/AWr/ARr/ARr/ARr/ARrTQv82Dv82Ds5M/1qhyUb0WqHMSP9bT/9bT85M/10i/10izkz/XQjHRP4Ha/9c7ctI/gQ8/1zSx0T+BDP/AWj/AWj/Afz/AfzZSP8C0v8C0v8DXP8DXP8D5/8D5/8Ed/8Ed/8Ed/8Gff8GfdZP/wZ9/wZ9zE3WSP9Yw85D/1io/liozEn/WI7+WI7MSf9YdP5YdMxJ/00Z/00Z0E7/WED/WEDmWEDMUP8K2P8K2P8K2MpM/wrY/wqTyUf/CpP/CpP/CpP/CpPEUv8M6MZD/gMt/w1uxkP/FEH/DhDEUf8OEN1f/w62yUf/Drb/D4TJR/8Xa/8QFMtJ/gM6/xH0/xH02lH/EWT/EWTTV/9Ty/9Ty81L/1Owx0X/G8v/E4n/E4n+Asv/FC3KR/4DVcUm/xTRxyP/FNHTXf8Vff8Vff8GEP8GEP8GEP8gCcxb/yAJ/yAJ/wEG/wEG/wGy/wGy/wGy013/F9f/F9fXVf8X1/8X19VT/xkX/xkXzEn/GRf/GRfQT/8aT/8aT81L/xpP/xpP11X/KHr/KHrNS/8oYP8oYNtZ/07L/07L1VP/TrD/TrDPTf9Olf9OldVT/056/0560U3/I9//I9/RUf8jjP8jjP8Chv8Chv8Cht9L30vfS99L30vfS99L30vfS99L30vfS8RL/yvp/yvp31XfVd9V31XfVd9Vx1X/E/7/E/7OTP8qC/4qb99J30nfSd9J30n/AXz/AXzaVf8pWMVD/ylY/yiw/yiw1VP/AOv/AOvfVd9V31X/BAb/BAbfS99L30vfS99L10v/Ar//Ar/fSd9J30nfSd9J/wIR/wIR31XfVd9V0VX/RSH/RSH/AKf/AKf/AKf/Anf/AnffS99L30v/AjD/AjDfSd9J30nfSd9J/wHG/wHG/wHG31XfVd9V31XfVdBV/yqo/yqoz03/Kqj/KqjNS/8qqMdF/yqo/yvc/yvc2Vf/ATT/ATT/ATT/ATTcS/8CIf8CIddV/wRG/wRGzUv/D6H/D6HbWf8EDf8EDf8BQv8BQv8BQv8BQv8BQv8AoP8AoP8AoP8BPv8BPv8B4P8B4P8B4P8BQv8BQtxL/wCk/wCk3Fn/AZv/AZvWVdlP/wGb/wFC/wFC/wFC/wFC/wFC21n/AUL/AULWVdlP/wFC30nfSd9J30nfSd9J30nfSd9J30nfSd9J30nfSd9J30nRSV19) of an example saved layout if you'd like to play around with it. It's pointing to localhost so you need to be on the branch of my fork in order to view it.

**Comment by plateupplanner** [comment]
I've pushed the following changes:

* Add a 2-character ID to each square and wall element
* Add encode/decode functions to convert a Layout into an LZ-compressed string, and vice versa
* Ensure the URL changes to include the layout string whenever the layout changes
* Add a button to copy the link to the clipboard
* Have the grid show up correctly when a layout is being imported (rather than created from new)

Closing this issue for now.
