### ISSUE TITLE
Dragging occasionally opens up an un-refreshable blank page

### ISSUE THREAD

**Issue by chriskorosu** [plateupplanner/plateupplanner.github.io#5]
Not sure how to reproduce exactly beyond just dragging a bunch of random items. It doesn't happen on every drag, but frequently enough to be an issue. 

The blank page is un-refreshable, so the only way to get back to the previous state is to copy/paste the URL into a new tab.

https://user-images.githubusercontent.com/47898552/194713185-05b6d390-d879-44cb-8e82-fbdd839eff6f.mp4

**Comment by chriskorosu** [comment]
Using Firefox 105.0.2 on Windows 10

**Comment by chriskorosu** [comment]
Doesn't seem reproducible on Chrome, so one workaround is to just use Chrome I guess

**Comment by plateupplanner** [comment]
Thanks for the bug report! This should be fixed, closing the issue for now. Let me know if you run into it again!

**Comment by chriskorosu** [comment]
Thanks for fixing it! I've been using PUP in Firefox without any issues since 💖
