### ISSUE TITLE
There don't seem to be any chairs (an important planning item)

### ISSUE THREAD

**Issue by jdsandifer** [plateupplanner/plateupplanner.github.io#7]
1. I don't see any chairs in the right side menu. Having them as an item would help with planning tight table arrangements.

1. Whether or not the chairs are listed in the inventory list wouldn't matter to me, but not including them in the list is probably ideal.

1. A bonus would be a feature that notices when chairs are pointing at adjacent tables and adds a tally number over the tables like in the game, but that isn't necessary for basic planning. Just a chair item that can be rotated like everything else would be enough. (If the tally were implemented, the numbers should probably be "transparent" to mouse clicks so interacting with the table underneath isn't affected.)

**Comment by plateupplanner** [comment]
Thanks for the suggestion! For the sake of organisation, I'm going to close this and put this in our feature suggestions channel in Discord.

**Comment by plateupplanner** [comment]
Hello, just a quick update to say that we've added chairs as an item you can add. It currently works like other items which is not ideal as you pointed out. We're prioritising other features right now but may come back to this later -- ideally I would like them to work like they do in the game!
